name: Dev to Test Sync and PR to Prod

on:
  push:
    branches:
      - dev

jobs:
  sync-to-test:
    name: Push Dev → QA, Run Tests, Create PR to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set Authenticated Remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Fetch All Branches
        run: git fetch --all

      - name: Checkout QA Branch
        run: |
          git checkout qa || git checkout -b qa
          git reset --hard origin/dev
          git push --force origin qa

  run-test-workflow:
    name: Trigger test workflow on QA branch
    needs: sync-to-test
    uses: ./.github/workflows/run-tests.yml
    with:
      ref: qa

  create-pr-to-prod:
    name: Create PR from QA to Prod
    needs: run-test-workflow
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Create PR using GitHub CLI
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "qa",
              base: "prod",
              state: "open",
            });

            if (pulls.length === 0) {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: "qa",
                base: "prod",
                title: "Promote QA → Prod",
                body: "Auto PR created after successful tests."
              });
            } else {
              console.log("PR already exists. Skipping creation.");
            }
